### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by didix21** [didix21/Shusky#1]
Create different types that can contain yaml. 

- PrecCommit
```yaml
precommit:
    - swift run command 1
    - swift run command 2
    - swift run command 3
    - run:
        command: swift run command 4
        path: ./path/where/to/run
```
- PostCommit
```yaml
postcommit:
    - swift run command 1
    - swift run command 2
    - swift run command 3
    - run:
        command: swift run command 4
        path: ./path/where/to/run
```
- PrePush
```yaml
prepush:
    - swift run command 1
    - swift run command 2
    - swift run command 3
    - run:
        command: swift run command 4
        path: ./path/where/to/run
```
- Run
```yaml
- run:
    command: swift run command 4
    path?: ./path/where/to/run
    critical?: true or false
    verbose: true or false
```
